apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          ports:
            - containerPort: 1010